import { Module } from '@nestjs/common';
import {
  TrackingMongoModule,
  RedisModule,
  TrackingPostgreSqlModule,
  PgApplicationSettingRepo,
  PgBusinessRepo,
  PgVehicleRepo,
  PgUserRepo,
  MongoTrackingDataRepository,
  PgScenarioSettingRepo,
  PgTrackerRepo,
  PgTrackingDeviceRepo,
  PgTrackingModelRepo,
  PgTrackingBrandRepo,
  PgIoParameterRepo,
  PgIoParameterValueRepo,
  PgTrackingExtensionRepo,
  PgTripRepo,
  PgTripAreaRepo,
  PgTrackerAssignmentRepo,
  PgTrackerLatestDataRepo,
  PgViolationRepo,
  PgUserVehicleAccessRepo,
  ApplicationScheduler,
  PgTrackingEventRepo,
  TripCreationConsumer,
  ScenarioSettingConsumer,
  TrackingDataClusteringSocketEvent,
  TrackingRealtimeDataConsumer,
  TrackerRealtimeEventConsumer,
  TransportVehicleBrokerSyncConsumer,
  TransportBusinessBrokerSyncConsumer,
  TransportUserBrokerSyncConsumer,
} from './infrastructure';
import {
  ApplicationSettingRepository,
  BusinessRepository,
  IoParameterRepository,
  IoParameterValueRepository,
  ScenarioSettingRepository,
  TrackerAssignmentRepository,
  TrackerLatestDataRepository,
  TrackerRepository,
  TrackingBrandRepository,
  TrackingDataRepository,
  TrackingDeviceRepository,
  TrackingEventRepository,
  TrackingExtensionRepository,
  TrackingModelRepository,
  TripAreaRepository,
  TripRepository,
  UserRepository,
  UserVehicleAccessRepository,
  VehicleRepository,
  ViolationRepository,

} from './domain';
import {
  AuthService, AuthServiceImp,
  ApplicationSettingGetQueryHandler,
  ViolationGridQueryHandler,
  BusinessSyncCommandHandler,
  UserSyncCommandHandler,
  VehicleSyncCommandHandler,
  ApplicationSettingUpdateCommandHandler,
  ViolationTrackedRouteQueryHandler,
  UserGridQueryHandler,
  UpdateUserVehicleAccessCommandHandler,
  UserUnassignVehiclesGridQueryHandler,
  UserAssignVehiclesGridQueryHandler,
  UserAssignVehiclesCommandHandler,
  UserUnassignVehiclesCommandHandler,
  VehicleAssignmentMobileGridQueryHandler,
  SyncManagementDataCommandHandler,
  GetDeviceTracingResultQueryHandler,
  TrackingExtensionGridQueryHandler,
  TrackingExtensionCreateCommandHandler,
  StartTraceDeviceCommandHandler,
  StopTraceDeviceCommandHandler,
  TrackingExtensionUpdateCommandHandler,
  GetTrackingExtensionByIdQueryHandler,
  TrackingExtensionChangeStatusCommandHandler,
  GetTrackingExtensionByExtensionIdQueryHandler,
  TrackerAssignmentMobileCommandHandler,
  SyncRegisterDevicesCommandHandler,
  TrackerAssignmentGridQueryHandler,
  EndTrackerAssignmentCommandHandler,
  TrackingBrandListQueryHandler,
  TrackingModelListQueryHandler,
  VehicleListQueryHandler,
  TrackingDeviceCheckByImeiQueryHandler,
  TrackerAssignmentCreateCommandHandler,
  TrackerAssignmentUpdateCommandHandler,
  TrackerAssignmentUpdateInfoQueryHandler,
  PublicRegisterTrackerCommandHandler,
  PublicEndTrackerAssignmentCommandHandler,
  PublicTrackerAssignmentUpdateCommandHandler,
  GetGeoLocationAddressQueryHandler,
  GetWeatherDataQueryHandler,
  TrackingEventGridQueryHandler,
  TrackingEventDetailQueryHandler,
  TrackingEventAssignmentGridQueryHandler,
  GetExtensionLatestLocationQueryHandler,
  TripGridQueryHandler,
  TrackingDeviceSendCommandCommandHandler,
  GetSupportedCommandQueryHandler,
  TrackerAssignmentInfoQueryHandler,
  GetCurrentDriverQueryHandler,
  TrackerGridQueryHandler,
  GetTrackerSummaryStatusQueryHandler,
  GetPointDetailsQueryHandler,
  GetTrackerAssignmentListQueryHandler,
  GetTrackerAssignmentStatusQueryHandler,
  GetDataHistoryQueryHandler,
  GetTrackersLatestLocationQueryHandler,
  GetNearbyVehicleQueryHandler,
  GetVehicleTrackingInfoQueryHandler,
  TripCreationCommandHandler,
  ScenarioSettingCommandHandler,
  TrackerRealtimeEventCommandHandler,
  AssignmentRealtimeDataCommandHandler,
  TransportVehicleBrokerSyncCommandHandler,
  TransportBusinessBrokerSyncCommandHandler,
  TransportUserBrokerSyncCommandHandler,
  GetTripTrackedRouteSummaryQuery,
  TripTrackedRouteQueryHandler,
  IoParameterListQueryHandler,
  GetPublicTrackingDataQueryHandler,
  GetDataHistoryTrackedRouteQueryHandler,
  GetCurrentTripInfoQueryHandler,
  GetTripQueryHandler,
  GetTrackerAssignmentSummaryQueryHandler,
  GetTrackerAssignmentMovementSummaryQueryHandler,
  GetDataHistoryTrackedParameterQueryHandler,
  GetTripTrackedRouteSummaryQueryHandler,
} from './application';
import { GridUtilsService, HTTP_CONSTANT, HttpModule } from 'src/common';
import { AppConfigService } from 'src/config';
import {
  ApplicationSettingController,
  BusinessController,
  UserController,
  VehicleController,
  ViolationController,
  SynchronizationController,
  TripController,
  MonitoringController,
  TrackingExtensionController,
  TrackerAssignmentController,
  TrackingBrandController,
  TrackingModelController,
  TrackingDeviceController,
  PublicServicesController,
  LocationController,
  TrackingEventController,
  TrackerController,
  PanelController
} from './presentation';
import { CommonModule } from 'src/common/common.module';
@Module({
  imports: [
    RedisModule,
    TrackingMongoModule,
    TrackingPostgreSqlModule,
    CommonModule,
    HttpModule.forFeature([
      {
        serviceName: HTTP_CONSTANT.SERVICES.TRANSPORT.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.sync.singleEndpoint.url,
          enableLogging: true,
          rejectUnauthorized:false
        }),
      },
      {
        serviceName: HTTP_CONSTANT.SERVICES.CORE.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.sync.multipleEndpoints.coreUrl,
          enableLogging: true,
          rejectUnauthorized:false
        }),
      },
      {
        serviceName: HTTP_CONSTANT.SERVICES.FLEET.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.sync.multipleEndpoints.fleetUrl,
          enableLogging: true,
          rejectUnauthorized:false
        }),
      },
      {
        serviceName: HTTP_CONSTANT.SERVICES.AUTH.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.auth.authority,
          enableLogging: true,
          rejectUnauthorized:false
        }),
      },
      {
        serviceName: HTTP_CONSTANT.SERVICES.TRACKING_AGENT.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.trackingAgent.url,
          rejectUnauthorized:false
        }),
      },
      {
        serviceName: HTTP_CONSTANT.SERVICES.NESHAN.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.neshanApi.url,
        }),
      },
      {
        serviceName: HTTP_CONSTANT.SERVICES.OPEN_WEATHER.SERVICE_NAME,
        config: (appConfigService: AppConfigService) => ({
          baseURL: appConfigService.openWeatherApi.url,
          defaultTimeout: 5000, // 5 seconds for OpenWeather
        }),
      },
    ]),
  ],
  controllers: [
    ApplicationSettingController,
    BusinessController,
    VehicleController,
    UserController,
    ViolationController,
    SynchronizationController,
    TripController,
    MonitoringController,
    TrackingExtensionController,
    TrackerAssignmentController,
    TrackingBrandController,
    TrackingModelController,
    TrackingDeviceController,
    PublicServicesController,
    LocationController,
    TrackingEventController,
    TrackerController,
    PanelController
  ],
  providers: [GridUtilsService,
    {
      provide: AuthService,
      useClass: AuthServiceImp
    },
    {
      provide: ApplicationSettingRepository,
      useClass: PgApplicationSettingRepo,
    },
    {
      provide: BusinessRepository,
      useClass: PgBusinessRepo,
    },
    {
      provide: VehicleRepository,
      useClass: PgVehicleRepo,
    },
    {
      provide: UserRepository,
      useClass: PgUserRepo,
    },
    {
      provide: TrackingDataRepository,
      useClass: MongoTrackingDataRepository,
    },
    {
      provide: ScenarioSettingRepository,
      useClass: PgScenarioSettingRepo,
    },
    {
      provide: TrackerRepository,
      useClass: PgTrackerRepo,
    },
    {
      provide: TrackingDeviceRepository,
      useClass: PgTrackingDeviceRepo,
    },
    {
      provide: TrackingModelRepository,
      useClass: PgTrackingModelRepo,
    },
    {
      provide: TrackingBrandRepository,
      useClass: PgTrackingBrandRepo,
    },
    {
      provide: IoParameterRepository,
      useClass: PgIoParameterRepo,
    },
    {
      provide: IoParameterValueRepository,
      useClass: PgIoParameterValueRepo,
    },
    {
      provide: TrackingExtensionRepository,
      useClass: PgTrackingExtensionRepo,
    },
    {
      provide: TripRepository,
      useClass: PgTripRepo,
    },
    {
      provide: TripAreaRepository,
      useClass: PgTripAreaRepo,
    },
    {
      provide: TrackerAssignmentRepository,
      useClass: PgTrackerAssignmentRepo,
    },
    {
      provide: TrackerLatestDataRepository,
      useClass: PgTrackerLatestDataRepo,
    },
    {
      provide: ViolationRepository,
      useClass: PgViolationRepo,
    },
    {
      provide: UserVehicleAccessRepository,
      useClass: PgUserVehicleAccessRepo,
    },
    {
      provide: TrackingEventRepository,
      useClass: PgTrackingEventRepo,
    },

    TrackingDataClusteringSocketEvent,


    ApplicationSettingUpdateCommandHandler,
    BusinessSyncCommandHandler,
    VehicleSyncCommandHandler,
    UserSyncCommandHandler,
    UpdateUserVehicleAccessCommandHandler,
    UserAssignVehiclesCommandHandler,
    UserUnassignVehiclesCommandHandler,
    SyncManagementDataCommandHandler,
    StartTraceDeviceCommandHandler,
    StopTraceDeviceCommandHandler,
    TrackingExtensionCreateCommandHandler,
    TrackingExtensionUpdateCommandHandler,
    TrackingExtensionChangeStatusCommandHandler,
    TrackerAssignmentMobileCommandHandler,
    SyncRegisterDevicesCommandHandler,
    EndTrackerAssignmentCommandHandler,
    TrackerAssignmentCreateCommandHandler,
    TrackerAssignmentUpdateCommandHandler,
    PublicRegisterTrackerCommandHandler,
    PublicEndTrackerAssignmentCommandHandler,
    PublicTrackerAssignmentUpdateCommandHandler,
    TrackingDeviceSendCommandCommandHandler,
    TripCreationCommandHandler,
    ScenarioSettingCommandHandler,
    AssignmentRealtimeDataCommandHandler,
    TrackerRealtimeEventCommandHandler,
    TransportVehicleBrokerSyncCommandHandler,
    TransportBusinessBrokerSyncCommandHandler,
    TransportUserBrokerSyncCommandHandler,


    ApplicationSettingGetQueryHandler,
    ViolationGridQueryHandler,
    ViolationTrackedRouteQueryHandler,
    UserGridQueryHandler,
    UserAssignVehiclesGridQueryHandler,
    UserUnassignVehiclesGridQueryHandler,
    VehicleAssignmentMobileGridQueryHandler,
    GetCurrentTripInfoQueryHandler,
    GetTripQueryHandler,
    GetDeviceTracingResultQueryHandler,
    TrackingExtensionGridQueryHandler,
    GetTrackingExtensionByIdQueryHandler,
    GetTrackingExtensionByExtensionIdQueryHandler,
    TrackerAssignmentGridQueryHandler,
    TrackingModelListQueryHandler,
    TrackingBrandListQueryHandler,
    VehicleListQueryHandler,
    TrackingDeviceCheckByImeiQueryHandler,
    TrackerAssignmentUpdateInfoQueryHandler,
    GetGeoLocationAddressQueryHandler,
    GetWeatherDataQueryHandler,
    TrackingEventGridQueryHandler,
    TrackingEventDetailQueryHandler,
    TrackingEventAssignmentGridQueryHandler,
    GetExtensionLatestLocationQueryHandler,
    TripGridQueryHandler,
    GetSupportedCommandQueryHandler,
    TrackerAssignmentInfoQueryHandler,
    GetCurrentDriverQueryHandler,
    TrackerGridQueryHandler,
    GetTrackerSummaryStatusQueryHandler,
    GetPointDetailsQueryHandler,
    GetTrackerAssignmentListQueryHandler,
    GetTrackerAssignmentStatusQueryHandler,
    GetDataHistoryQueryHandler,
    GetTrackersLatestLocationQueryHandler,
    GetNearbyVehicleQueryHandler,
    GetVehicleTrackingInfoQueryHandler,
    GetTripTrackedRouteSummaryQuery,
    TripTrackedRouteQueryHandler,
    IoParameterListQueryHandler,
    GetPublicTrackingDataQueryHandler,
    GetDataHistoryTrackedRouteQueryHandler,
    GetTrackerAssignmentSummaryQueryHandler,
    GetTrackerAssignmentMovementSummaryQueryHandler,
    GetDataHistoryTrackedParameterQueryHandler,
    GetTripTrackedRouteSummaryQueryHandler,

    TripCreationConsumer,
    ScenarioSettingConsumer,
    TrackingRealtimeDataConsumer,
    TrackerRealtimeEventConsumer,
    TransportVehicleBrokerSyncConsumer,
    TransportBusinessBrokerSyncConsumer,
    TransportUserBrokerSyncConsumer,
    ApplicationScheduler
  ],
})
export class TrackingModule { }
